language: scala

sudo: required

services:
  - docker

jdk: oraclejdk8

scala:
  - 2.11.11

script:
  - sbt test

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - sbt assembly dockerBuildAndPush

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  branch: md5deep
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
  - "$HOME/.coursier"

env:
  global:
  - secure: "rAhyrKnXWcM9LqIg66mXmrMoACdQZ5UeYWukWL7rNEiLnnFM5PaORzwIzC+MijY7PSjGn6xCovYAT6UxneY7TsUU6CQO3kEE/RZL3DGWahGJFyQ0nEp9UneLY7qPobfjNbmCfzrxHT8bFVDV3ohpXxYiKwtGBWVzTziMczql+iEcAVE451ocC3c8V24KrnsL57vyvTelAExlD4YlpD357jR+USYu6JFqprbZPcI3VpX61jh1ZAmnaw5/Z5IUGUspK8Hk2rIcfDuk1OyNqk640SwlNexCz4WAtboKELsqnSxxDf+JbWe/kT8BjqswBdp0cmZ0uLtD4RoBfVvfai08Bm+QrkuoT3XO1KKodvGLZ6U6KN9YqtjsCumXRaw4D2UHIiLVX/o3FIlK350PTReg2C+5TEvbzgbazCxIIm9wYpoO7mKeYKt8Yy7YWvJlzJDl4LE1ABWhXrYwuogni2wC/L2rJVjKHipdhG2AgecR7t2UAK/PlzQk+lKtMhWUB6KhCuJIyuFB0rJ8KOeFZkn6ooLMw8OEGAHFXKEimET6ivsH0dvH3RI+6pMyob97uaSFvZLUFeH+oVzyVeQtlu4gI3H9+CWilRr8sud+3PuTpC6brNOb4bC6UWu+X/T/b3B+yKrjpLUjTtTojImenLDHRXokb/HrNTMnf2pAoqNcuR8="
  - secure: "Yll0fcLMikkLC6W1jpP/Ca+azi42kJkneQac1MMDphPSfqhA57nqY5EQnQm0MsMfOvKvNLy3ry3V8SMBH/ZS2jMGwotRq0P7QMDE/zSpKxOYLS4kZipTKOzgO9mqggNXn3lKauNyPQF/wMZh/LWhaEwfpIFPtFbCzRinLxpVGksVBTxsSi8KL7oFE6PfpYNES/msFDWg9g9ZCg1YTPn3jpoBwrdYCk1/sMsaoe/FCxse5sCf/P/o4iiCDk1IHqRV0vhnXlGgif3b4E7a9fBrG9gm511DQqaV0mJmBQ0z6LAVe2+kVwy388zpnJJI4GaPyCUbEnET5DiMh6JstiVzukLw5MLNJSSE1QFV/AiXC/taIhoDbaqSGOv0bgMuFj2WDAZCBuRvMJ/oHORGeufYu8WPsfVgCoXAl7LSfG1msRlD+X39xKt4qtHYw6TjOq4MI1S60SXtz9Kymb5jQBvwzHlgxrz4Um7r//LVy+PFTxVmD0zNxV7zHrTpjvfkYSCuYgQReodV6ng/7aVFMWJ1H/46NJEPHdNr0bI2dm/4D9QZcO2Ls8LSek9AMwWQ881I10oIsAktzYRvVW7Z0jC510E+a+RIL4ZeT659sV0i3H1B5Oc3S4JNhBYmyUHh5O0G/uorGbEOBnWskJM2x/77IfS6eVH6tH0Rxz4PXscilzY="
