language: scala

sudo: required

services:
  - docker

jdk: oraclejdk8

scala:
  - 2.11.11

script:
  - sbt test

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - sbt assembly dockerBuildAndPush

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  branch: md5deep
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
  - "$HOME/.coursier"

env:
  global:
  - secure: "EeWtYmo4pgIYSiuu3NV+dp5AbF9uQh2UE3DpeUEuWo+5vxXxrs5OvqggB0e6guRADrl/ro/h2aLi7OLbW51lCffTP9ex7rI4eCBusXadWhtga55MlAtxqvyLty8EGSdQAtKgwrWvLA2umDriIFmw3xOpplIghvnpXvqpWEhDdDViTHmZvLe6X3/OkxxDZPPXh6bXIOJiIIGiRFYHER3N2fpskXvY92U/kvrhXG/KA9V5a2XBU44PBpMvKfBTKsV7tJpj2JCK9IS2mTZ1s+V3MY0ysMtZo0iiv0/OW87uSly/TlFBYDtY/UnZljiw1W/ishX8rTo/SrktoA7gknJ2eBfcPxGr0y65atRdrBwi/nohc/GY/sE9tdu/hhz9E8zyFrHnZ/ULR79jaRwt/9CZSaQmtnS5s6ckN4/1xRTsobdSZ5d2WDJwnIELSX3/dbGRt74H+uZyio0fObteT8sXf2cXHX0zpkn3xLBXGq7IZ973GenShcy1kkCzabtbLbdPaOGowuRE3Vjpvt+K3vIVlAIJr3K92tuTt6roTORQ1VRrhRRdDdWGmeM784gkyHu9ALKorb8b42ZswJuuGvof34evBTJb/Rp88dzBU1DBI430Kwnl4nMSW/+Zdz/ellTlBeMmgv2X7AvQFZgAahfhW5ojioh4I1+f4pqvnuQd3ow="
  - secure: "Yll0fcLMikkLC6W1jpP/Ca+azi42kJkneQac1MMDphPSfqhA57nqY5EQnQm0MsMfOvKvNLy3ry3V8SMBH/ZS2jMGwotRq0P7QMDE/zSpKxOYLS4kZipTKOzgO9mqggNXn3lKauNyPQF/wMZh/LWhaEwfpIFPtFbCzRinLxpVGksVBTxsSi8KL7oFE6PfpYNES/msFDWg9g9ZCg1YTPn3jpoBwrdYCk1/sMsaoe/FCxse5sCf/P/o4iiCDk1IHqRV0vhnXlGgif3b4E7a9fBrG9gm511DQqaV0mJmBQ0z6LAVe2+kVwy388zpnJJI4GaPyCUbEnET5DiMh6JstiVzukLw5MLNJSSE1QFV/AiXC/taIhoDbaqSGOv0bgMuFj2WDAZCBuRvMJ/oHORGeufYu8WPsfVgCoXAl7LSfG1msRlD+X39xKt4qtHYw6TjOq4MI1S60SXtz9Kymb5jQBvwzHlgxrz4Um7r//LVy+PFTxVmD0zNxV7zHrTpjvfkYSCuYgQReodV6ng/7aVFMWJ1H/46NJEPHdNr0bI2dm/4D9QZcO2Ls8LSek9AMwWQ881I10oIsAktzYRvVW7Z0jC510E+a+RIL4ZeT659sV0i3H1B5Oc3S4JNhBYmyUHh5O0G/uorGbEOBnWskJM2x/77IfS6eVH6tH0Rxz4PXscilzY="
